#! pvztoolkit

# 在线下载知名阵型列表:
# https://pvz.lmintlcx.com/lineup/

# 文件位于主程序同一目录时会自动加载.
# 后缀名为 ".yml", 所用格式是 YAML 的子集.
# 编码格式为 UTF-8.
# 第一行必须是 "#! pvztoolkit".
# 空行会被忽略.
# 井号 "#" 开头的行是注释, 会被忽略.
# 每一行表示一个阵型.
# 阵型包含名称和代码两个部分, 用冒号空格隔开 ": ".
# 阵型名称必须加上双引号, 阵型代码不加.
# 上述标点符号均为英文.
# 阵型名称可以用中英文和数字, 尽量不要用特殊字符.
# 格式错误的行会被忽略.

"[终极战术] 五角星无炮流": LI43jH/kRlzjZrhRF3RUpjJeOFHFZEXTHtMe0tlawVVE7GI0efJc8npSWMdVLhV261Y=
